name: Update Postman Collection

on:
  push:
    branches:
      - main
    paths:
      - .github/index.yaml

jobs:
  update-postman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Newman CLI
        run: npm install -g newman

      - name: Update Postman Collection via Postman API
        env:
          POSTMAN_API_KEY: ${{ POSTMAN_API_KEY }}
        run: |
          curl -X PUT https://api.getpostman.com/collections/zr10quo \
          -H "X-Api-Key: $POSTMAN_API_KEY" \
          -d @path/to/openapi/file.yaml
