name: Sync Postman Collection to Postman API
 
on:
  push:
    paths:
      - 'collection.json'
    branches:
      - main
 
jobs:
  sync-to-postman:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
 
      - name: Upload to Postman
        run: |
          curl --location --request PUT "https://api.getpostman.com/collections/${{ secrets.POSTMAN_COLLECTION_UID }}" \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
          --header "Content-Type: application/json" \
          --data "@collection.json"
