name: Sync Postman Collection to Postman API

on:
  push:
    paths:
      - '.github/index.json'
    branches:
      - main

jobs:
  update-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync collection to Postman
        run: |
          curl --location --request PUT "https://api.getpostman.com/collections/${{ secrets.POSTMAN_COLLECTION_UID }}" \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
          --header "Content-Type: application/json" \
          --data "@.github/index.json"
